# Generated by Django 3.0.8 on 2021-01-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20201009_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Great',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('slug', models.SlugField(allow_unicode=True, null=True, verbose_name='اسلاگ')),
                ('father_name', models.CharField(max_length=30, verbose_name='نام پدر')),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True, verbose_name='محل تولد')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('post', models.CharField(blank=True, max_length=50, null=True, verbose_name='سمت و مقام')),
                ('biography', models.TextField(verbose_name='زندگینامه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='great/images', verbose_name='عکس')),
                ('clip', models.FileField(upload_to='great/clips', verbose_name='کلیپ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'بزرگان',
                'verbose_name_plural': 'بزرگان',
            },
        ),
        migrations.AddField(
            model_name='soghat',
            name='category2',
            field=models.CharField(blank=True, choices=[('F', 'خوراکی'), ('D', 'صنایع دستی')], default='F', max_length=1, null=True, verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='SoghatImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='soghat/soghat_images', verbose_name='تصویر')),
                ('soghat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.Soghat', verbose_name='سوغات')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر',
            },
        ),
        migrations.CreateModel(
            name='PlaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='place/place_images', verbose_name='تصویر')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.Place', verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر',
            },
        ),
        migrations.CreateModel(
            name='Martyrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('slug', models.SlugField(allow_unicode=True, null=True, verbose_name='اسلاگ')),
                ('father_name', models.CharField(max_length=30, verbose_name='نام پدر')),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True, verbose_name='محل تولد')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('post', models.CharField(blank=True, max_length=50, null=True, verbose_name='سمت و مقام')),
                ('place_of_death', models.CharField(blank=True, max_length=50, null=True, verbose_name='محل شهادت')),
                ('date_of_death', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شهادت')),
                ('operation', models.CharField(blank=True, max_length=30, null=True, verbose_name='عملیات')),
                ('biography', models.TextField(verbose_name='زندگینامه')),
                ('image', models.ImageField(upload_to='martyrs/images', verbose_name='عکس')),
                ('clip', models.FileField(upload_to='martyrs/clips', verbose_name='کلیپ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'شهید',
                'verbose_name_plural': 'شهید',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, null=True, verbose_name='اسلاگ')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='hotel/images', verbose_name='عکس')),
                ('clip', models.FileField(upload_to='hotel/clips', verbose_name='کلیپ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل',
            },
        ),
        migrations.CreateModel(
            name='GreatServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='خدمت')),
                ('great', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.Great', verbose_name='نام بزرگ')),
            ],
            options={
                'verbose_name': 'خدمات بزرگان',
                'verbose_name_plural': 'خدمات بزرگان',
            },
        ),
        migrations.CreateModel(
            name='AttrHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=200, verbose_name='ویژگی')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.Hotel', verbose_name='نام هتل')),
            ],
            options={
                'verbose_name': 'ویژگی ها',
                'verbose_name_plural': 'ویژگی',
            },
        ),
    ]
