# Generated by Django 3.0.8 on 2021-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_auto_20210125_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='martyrs',
            options={'verbose_name': 'شهید', 'verbose_name_plural': 'شهدا'},
        ),
        migrations.AlterField(
            model_name='city',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='dialect',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='گویش'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='great',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='زندگینامه'),
        ),
        migrations.AlterField(
            model_name='great',
            name='clip',
            field=models.FileField(blank=True, null=True, upload_to='great/clips', verbose_name='کلیپ'),
        ),
        migrations.AlterField(
            model_name='great',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='great',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='great',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='great/images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='clip',
            field=models.FileField(blank=True, null=True, upload_to='hotel/clips', verbose_name='کلیپ'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='martyrs',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='زندگینامه'),
        ),
        migrations.AlterField(
            model_name='martyrs',
            name='clip',
            field=models.FileField(blank=True, null=True, upload_to='martyrs/clips', verbose_name='کلیپ'),
        ),
        migrations.AlterField(
            model_name='martyrs',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='martyrs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='martyrs/images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='place', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='soghat',
            name='category2',
            field=models.CharField(blank=True, choices=[('F', 'خوراکی'), ('D', 'صنایع دستی')], default='F', max_length=1, null=True, verbose_name='زیر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='soghat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='soghat', verbose_name='عکس'),
        ),
    ]
