# Generated by Django 3.0.8 on 2021-01-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_auto_20210125_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='great',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='great',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='martyrs',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='martyrs',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شهادت'),
        ),
    ]
