# Generated by Django 3.0.8 on 2021-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0007_auto_20210125_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soghat',
            old_name='category2',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='hotel',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('H', 'هتل'), ('R', 'رستوران')], max_length=1, null=True, verbose_name='زیر دسته بندی'),
        ),
    ]
