# Generated by Django 3.0.8 on 2021-01-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0008_auto_20210125_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'هتل و رستوران', 'verbose_name_plural': 'هتل و رستوران'},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='place',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
    ]
