# Generated by Django 3.0.8 on 2021-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0009_auto_20210125_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='martyrs',
            name='will',
            field=models.TextField(blank=True, null=True, verbose_name='وصیت نامه'),
        ),
    ]
