# Generated by Django 3.0.8 on 2021-01-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0011_auto_20210125_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن'),
        ),
    ]
