# Generated by Django 3.0.8 on 2021-04-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0014_auto_20210409_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categorys', verbose_name='عکس'),
        ),
    ]
