# Generated by Django 3.0.8 on 2021-04-13 15:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0015_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='great',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='martyrs',
            old_name='fullname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات'),
        ),
    ]
