# Generated by Django 3.0.8 on 2021-07-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0017_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام آیکون'),
        ),
    ]
