# Generated by Django 3.0.8 on 2021-07-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0018_category_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='family',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تعداد خانوار'),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='جمعیت'),
        ),
        migrations.AddField(
            model_name='city',
            name='village',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تعداد روستاها'),
        ),
    ]
