# Generated by Django 3.0.8 on 2021-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0019_auto_20210704_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='great',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='martyrs',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='place',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='soghat',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
