# Generated by Django 3.0.8 on 2021-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0020_auto_20210705_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='great',
            name='is_access',
            field=models.BooleanField(default=False, verbose_name='تأیید'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_access',
            field=models.BooleanField(default=False, verbose_name='تأیید'),
        ),
        migrations.AddField(
            model_name='martyrs',
            name='is_access',
            field=models.BooleanField(default=False, verbose_name='تأیید'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_access',
            field=models.BooleanField(default=False, verbose_name='تأیید'),
        ),
        migrations.AddField(
            model_name='soghat',
            name='is_access',
            field=models.BooleanField(default=False, verbose_name='تأیید'),
        ),
    ]
