# Generated by Django 3.0.8 on 2021-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0022_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
