# Generated by Django 3.0.8 on 2021-07-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0023_ipclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='city.IpClass', verbose_name='دیسلایک'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='city.IpClass', verbose_name='لایک'),
        ),
    ]
